### PR TITLE
added command line param for specifying private key passphrase

### PR DESCRIPTION
**Pull request by angad**
Needed this for some automation

### CODE REVIEW

**Comment by jschauma** [comment]
I'm not usually a fan of allowing users to specify passphrases on the command-line, but I do understand the need for a method to provide it non-interactively in some cases.

I'd be inclined to mirror openssl(1)'s behaviour and accept multiple methods (passphrase, env, file) to allow the user to choose the least-worst, although that's a bit more effort than this patch.

(Also, for future reference, an update to the manual page at the same time would be ideal. :-)

**Comment by angad** [comment]
I took a look at openssl passhphrase options - and indeed, it has multiple methods of providing it. 

For reference (http://linux.die.net/man/1/openssl)

> Pass Phrase Arguments
> 
> Several commands accept password arguments, typically using -passin and -passout for input and output passwords respectively. These allow the password to be obtained from a variety of sources. Both of these options take a single argument whose format is described below. If no password argument is given and a password is required then the user is prompted to enter one: this will typically be read from the current terminal with echoing turned off.
> 
> pass:password
> the actual password is password. Since the password is visible to utilities (like 'ps' under Unix) this form should only be used where security is not important.
> env:var
> obtain the password from the environment variable var. Since the environment of other processes is visible on certain platforms (e.g. ps under certain Unix OSes) this option should be used with caution.
> 
> file:pathname
> the first line of pathname is the password. If the same pathname argument is supplied to -passin and -passout arguments then the first line will be used for the input password and the next line for the output password. pathname need not refer to a regular file: it could for example refer to a device or named pipe.
>
> fd:number
> read the password from the file descriptor number. This can be used to send the data via a pipe for example.
> 
> stdin
> 
> read the password from standard input.

I will be happy to implement env variable support and file support.

**Comment by jschauma** [comment]
Awesome!  This should be straight forward, and we can probably stuff that logic into the 'getpass' function:

```
func getpass(prompt string) (pass []byte) {
    check pass option:
      if 'pass:passphrase', return passphrase
      if 'env:var', getenv(var) and return if success, abort with error otherwise
      if 'file:filename', read first line from filename, return
   else continue with regular tty prompt
```
I'd probably put the logic for each case into their own function; the manual page update can probably take wording from openssl(1) almost verbatim then.

**Comment by angad** [comment]
Added the options. Let me know if I missed anything.

**Comment by jschauma** [comment]
I've merged the pull request and added some tests in a subsequent commit.
Thanks for your changes!

**Comment by angad** [comment]
great, thanks!

**Pull request merged**
